# Generated by Django 5.2.5 on 2025-09-02 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(upload_to='services/images/', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/images', verbose_name='Imagen')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.service')),
            ],
            options={
                'verbose_name': 'Imagen de servicio',
                'verbose_name_plural': 'Imágenes de servicio',
            },
        ),
    ]
